// flow-typed signature: dab81070cd5b4aeedf052dab0f2ea514
// flow-typed version: <<STUB>>/async-to-generator_v^1.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-to-generator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-to-generator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-to-generator/async-to-generator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-to-generator/async-to-generator.js' {
  declare module.exports: $Exports<'async-to-generator/async-to-generator'>;
}
