// flow-typed signature: d5ebfb2867cc3acd8557b84dd07a410c
// flow-typed version: <<STUB>>/atom-languageclient_v0.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-languageclient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-languageclient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-languageclient/build/lib/adapters/autocomplete-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/document-sync-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/format-code-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/linter-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/notifications-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/nuclide-definition-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/nuclide-find-references-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/nuclide-hyperclick-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/adapters/nuclide-outline-view-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/auto-languageclient' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/convert' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/download-file' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/languageclient' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/logger' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/main' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/lib/server-manager' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/adapters/autocomplete-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/adapters/format-code-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/adapters/linter-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/convert.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/helpers' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/languageclient.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/build/test/runner' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/autocomplete-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/document-sync-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/format-code-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/linter-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/notifications-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/nuclide-definition-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/nuclide-find-references-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/nuclide-hyperclick-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/adapters/nuclide-outline-view-adapter' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/auto-languageclient' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/convert' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/download-file' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/languageclient' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/logger' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/main' {
  declare module.exports: any;
}

declare module 'atom-languageclient/lib/server-manager' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/adapters/autocomplete-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/adapters/format-code-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/adapters/linter-adapter.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/convert.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/helpers' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/languageclient.test' {
  declare module.exports: any;
}

declare module 'atom-languageclient/test/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-languageclient/build/lib/adapters/autocomplete-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/autocomplete-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/document-sync-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/document-sync-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/format-code-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/format-code-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/linter-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/linter-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/notifications-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/notifications-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/nuclide-definition-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/nuclide-definition-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/nuclide-find-references-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/nuclide-find-references-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/nuclide-hyperclick-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/nuclide-hyperclick-adapter'>;
}
declare module 'atom-languageclient/build/lib/adapters/nuclide-outline-view-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/adapters/nuclide-outline-view-adapter'>;
}
declare module 'atom-languageclient/build/lib/auto-languageclient.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/auto-languageclient'>;
}
declare module 'atom-languageclient/build/lib/convert.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/convert'>;
}
declare module 'atom-languageclient/build/lib/download-file.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/download-file'>;
}
declare module 'atom-languageclient/build/lib/languageclient.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/languageclient'>;
}
declare module 'atom-languageclient/build/lib/logger.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/logger'>;
}
declare module 'atom-languageclient/build/lib/main.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/main'>;
}
declare module 'atom-languageclient/build/lib/server-manager.js' {
  declare module.exports: $Exports<'atom-languageclient/build/lib/server-manager'>;
}
declare module 'atom-languageclient/build/test/adapters/autocomplete-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/adapters/autocomplete-adapter.test'>;
}
declare module 'atom-languageclient/build/test/adapters/format-code-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/adapters/format-code-adapter.test'>;
}
declare module 'atom-languageclient/build/test/adapters/linter-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/adapters/linter-adapter.test'>;
}
declare module 'atom-languageclient/build/test/convert.test.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/convert.test'>;
}
declare module 'atom-languageclient/build/test/helpers.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/helpers'>;
}
declare module 'atom-languageclient/build/test/languageclient.test.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/languageclient.test'>;
}
declare module 'atom-languageclient/build/test/runner.js' {
  declare module.exports: $Exports<'atom-languageclient/build/test/runner'>;
}
declare module 'atom-languageclient/lib/adapters/autocomplete-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/autocomplete-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/document-sync-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/document-sync-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/format-code-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/format-code-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/linter-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/linter-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/notifications-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/notifications-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/nuclide-definition-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/nuclide-definition-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/nuclide-find-references-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/nuclide-find-references-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/nuclide-hyperclick-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/nuclide-hyperclick-adapter'>;
}
declare module 'atom-languageclient/lib/adapters/nuclide-outline-view-adapter.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/adapters/nuclide-outline-view-adapter'>;
}
declare module 'atom-languageclient/lib/auto-languageclient.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/auto-languageclient'>;
}
declare module 'atom-languageclient/lib/convert.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/convert'>;
}
declare module 'atom-languageclient/lib/download-file.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/download-file'>;
}
declare module 'atom-languageclient/lib/languageclient.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/languageclient'>;
}
declare module 'atom-languageclient/lib/logger.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/logger'>;
}
declare module 'atom-languageclient/lib/main.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/main'>;
}
declare module 'atom-languageclient/lib/server-manager.js' {
  declare module.exports: $Exports<'atom-languageclient/lib/server-manager'>;
}
declare module 'atom-languageclient/test/adapters/autocomplete-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/test/adapters/autocomplete-adapter.test'>;
}
declare module 'atom-languageclient/test/adapters/format-code-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/test/adapters/format-code-adapter.test'>;
}
declare module 'atom-languageclient/test/adapters/linter-adapter.test.js' {
  declare module.exports: $Exports<'atom-languageclient/test/adapters/linter-adapter.test'>;
}
declare module 'atom-languageclient/test/convert.test.js' {
  declare module.exports: $Exports<'atom-languageclient/test/convert.test'>;
}
declare module 'atom-languageclient/test/helpers.js' {
  declare module.exports: $Exports<'atom-languageclient/test/helpers'>;
}
declare module 'atom-languageclient/test/languageclient.test.js' {
  declare module.exports: $Exports<'atom-languageclient/test/languageclient.test'>;
}
declare module 'atom-languageclient/test/runner.js' {
  declare module.exports: $Exports<'atom-languageclient/test/runner'>;
}
