// flow-typed signature: 5ac5960f12eb47b8276d1d55cebe6c0e
// flow-typed version: <<STUB>>/babel-plugin-transform-async-to-module-method_v^6.24.1/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-async-to-module-method'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-async-to-module-method' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-async-to-module-method/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-async-to-module-method/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-async-to-module-method/lib/index'>;
}
