// flow-typed signature: 2cf5e750ca982fcaffc608035fc72091
// flow-typed version: <<STUB>>/eslint-config-fbjs-opensource_v^1.0.0/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-fbjs-opensource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-fbjs-opensource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-fbjs-opensource/warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-fbjs-opensource/index' {
  declare module.exports: $Exports<'eslint-config-fbjs-opensource'>;
}
declare module 'eslint-config-fbjs-opensource/index.js' {
  declare module.exports: $Exports<'eslint-config-fbjs-opensource'>;
}
declare module 'eslint-config-fbjs-opensource/warning.js' {
  declare module.exports: $Exports<'eslint-config-fbjs-opensource/warning'>;
}
