// flow-typed signature: 6bbac71ccf131aa6a486f409e555642e
// flow-typed version: <<STUB>>/fuzzaldrin-plus_v^0.4.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzaldrin-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzaldrin-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus.min' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus.min' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/filter' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/fuzzaldrin' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/matcher' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/pathScorer' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/query' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/lib/scorer' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/src/lib/filter' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/src/lib/matcher' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/src/lib/pathScorer' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/src/lib/query' {
  declare module.exports: any;
}

declare module 'fuzzaldrin-plus/src/lib/scorer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus'>;
}
declare module 'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus.min.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/dist-browser/0.3.1/fuzzaldrin-plus.min'>;
}
declare module 'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus'>;
}
declare module 'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus.min.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/dist-browser/fuzzaldrin-plus.min'>;
}
declare module 'fuzzaldrin-plus/lib/filter.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/filter'>;
}
declare module 'fuzzaldrin-plus/lib/fuzzaldrin.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/fuzzaldrin'>;
}
declare module 'fuzzaldrin-plus/lib/matcher.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/matcher'>;
}
declare module 'fuzzaldrin-plus/lib/pathScorer.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/pathScorer'>;
}
declare module 'fuzzaldrin-plus/lib/query.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/query'>;
}
declare module 'fuzzaldrin-plus/lib/scorer.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/lib/scorer'>;
}
declare module 'fuzzaldrin-plus/src/lib/filter.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/src/lib/filter'>;
}
declare module 'fuzzaldrin-plus/src/lib/matcher.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/src/lib/matcher'>;
}
declare module 'fuzzaldrin-plus/src/lib/pathScorer.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/src/lib/pathScorer'>;
}
declare module 'fuzzaldrin-plus/src/lib/query.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/src/lib/query'>;
}
declare module 'fuzzaldrin-plus/src/lib/scorer.js' {
  declare module.exports: $Exports<'fuzzaldrin-plus/src/lib/scorer'>;
}
