// flow-typed signature: 33886a66dd3b9f11e32637508253e01f
// flow-typed version: <<STUB>>/ini_v^1.3.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ini'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ini' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ini/ini' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ini/ini.js' {
  declare module.exports: $Exports<'ini/ini'>;
}
