// flow-typed signature: 6e6f661754220127b221db50546fb9b5
// flow-typed version: <<STUB>>/nuclide-commons_v^0.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nuclide-commons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nuclide-commons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nuclide-commons/collection' {
  declare module.exports: any;
}

declare module 'nuclide-commons/debounce' {
  declare module.exports: any;
}

declare module 'nuclide-commons/event' {
  declare module.exports: any;
}

declare module 'nuclide-commons/nuclideUri' {
  declare module.exports: any;
}

declare module 'nuclide-commons/observable' {
  declare module.exports: any;
}

declare module 'nuclide-commons/promise' {
  declare module.exports: any;
}

declare module 'nuclide-commons/range' {
  declare module.exports: any;
}

declare module 'nuclide-commons/string' {
  declare module.exports: any;
}

declare module 'nuclide-commons/UniversalDisposable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nuclide-commons/collection.js' {
  declare module.exports: $Exports<'nuclide-commons/collection'>;
}
declare module 'nuclide-commons/debounce.js' {
  declare module.exports: $Exports<'nuclide-commons/debounce'>;
}
declare module 'nuclide-commons/event.js' {
  declare module.exports: $Exports<'nuclide-commons/event'>;
}
declare module 'nuclide-commons/nuclideUri.js' {
  declare module.exports: $Exports<'nuclide-commons/nuclideUri'>;
}
declare module 'nuclide-commons/observable.js' {
  declare module.exports: $Exports<'nuclide-commons/observable'>;
}
declare module 'nuclide-commons/promise.js' {
  declare module.exports: $Exports<'nuclide-commons/promise'>;
}
declare module 'nuclide-commons/range.js' {
  declare module.exports: $Exports<'nuclide-commons/range'>;
}
declare module 'nuclide-commons/string.js' {
  declare module.exports: $Exports<'nuclide-commons/string'>;
}
declare module 'nuclide-commons/UniversalDisposable.js' {
  declare module.exports: $Exports<'nuclide-commons/UniversalDisposable'>;
}
