// flow-typed signature: 42c42c6a1def4be93f6bc28a5a591fbc
// flow-typed version: <<STUB>>/shell-quote_v^1.6.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shell-quote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shell-quote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'shell-quote/index' {
  declare module.exports: $Exports<'shell-quote'>;
}
declare module 'shell-quote/index.js' {
  declare module.exports: $Exports<'shell-quote'>;
}
