// flow-typed signature: 6cbf8710a67c104651d3ac0d7b12818c
// flow-typed version: <<STUB>>/simple-text-buffer_v^9.2.11/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-text-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-text-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simple-text-buffer/lib/helpers' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/history' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/is-character-pair' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/match-iterator' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/patch' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/point-helpers' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/point' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/range' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/set-helpers' {
  declare module.exports: any;
}

declare module 'simple-text-buffer/lib/text-buffer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simple-text-buffer/lib/helpers.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/helpers'>;
}
declare module 'simple-text-buffer/lib/history.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/history'>;
}
declare module 'simple-text-buffer/lib/is-character-pair.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/is-character-pair'>;
}
declare module 'simple-text-buffer/lib/match-iterator.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/match-iterator'>;
}
declare module 'simple-text-buffer/lib/patch.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/patch'>;
}
declare module 'simple-text-buffer/lib/point-helpers.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/point-helpers'>;
}
declare module 'simple-text-buffer/lib/point.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/point'>;
}
declare module 'simple-text-buffer/lib/range.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/range'>;
}
declare module 'simple-text-buffer/lib/set-helpers.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/set-helpers'>;
}
declare module 'simple-text-buffer/lib/text-buffer.js' {
  declare module.exports: $Exports<'simple-text-buffer/lib/text-buffer'>;
}
