// flow-typed signature: bd99f3b5c62a276933fbd256bd0f41bc
// flow-typed version: <<STUB>>/through_v^2.3.6/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'through'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'through' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'through/index' {
  declare module.exports: $Exports<'through'>;
}
declare module 'through/index.js' {
  declare module.exports: $Exports<'through'>;
}
