// flow-typed signature: b31888916d21c0c134d6f76561c793ce
// flow-typed version: <<STUB>>/vscode-languageserver-types_v^3.2.0/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageserver-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageserver-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageserver-types/lib/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageserver-types/lib/main.js' {
  declare module.exports: $Exports<'vscode-languageserver-types/lib/main'>;
}
