// flow-typed signature: ea3d31321e1fdd19f12c3d3153a4eb9f
// flow-typed version: <<STUB>>/vscode-uri_v^1.0.0/flow_v0.44.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-uri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-uri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-uri/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-uri/lib/index.js' {
  declare module.exports: $Exports<'vscode-uri/lib/index'>;
}
