// flow-typed signature: 2417a3e5d0fb055436d81e6b94269632
// flow-typed version: <<STUB>>/vscode-languageserver_v^3.2.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-languageserver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-languageserver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-languageserver/lib/files' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/main' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/protocol' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/resolve' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/thenable' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/utils/is' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/utils/linkedMap' {
  declare module.exports: any;
}

declare module 'vscode-languageserver/lib/utils/uuid' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-languageserver/lib/files.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/files'>;
}
declare module 'vscode-languageserver/lib/main.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/main'>;
}
declare module 'vscode-languageserver/lib/protocol.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/protocol'>;
}
declare module 'vscode-languageserver/lib/resolve.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/resolve'>;
}
declare module 'vscode-languageserver/lib/thenable.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/thenable'>;
}
declare module 'vscode-languageserver/lib/utils/is.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/utils/is'>;
}
declare module 'vscode-languageserver/lib/utils/linkedMap.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/utils/linkedMap'>;
}
declare module 'vscode-languageserver/lib/utils/uuid.js' {
  declare module.exports: $Exports<'vscode-languageserver/lib/utils/uuid'>;
}
