// flow-typed signature: d55f0a0f4bad0b6828feeba0a5b477cf
// flow-typed version: <<STUB>>/xdg-basedir_v^3.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xdg-basedir'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xdg-basedir' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'xdg-basedir/index' {
  declare module.exports: $Exports<'xdg-basedir'>;
}
declare module 'xdg-basedir/index.js' {
  declare module.exports: $Exports<'xdg-basedir'>;
}
